-- MORDISCO OS V5 — INVENTARIO
-- Ejecuta todo este archivo en Supabase > SQL Editor > New query.

create table if not exists public.ingredients (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  unit text not null default 'unidad',
  cost_per_unit numeric(14,4) not null default 0 check (cost_per_unit >= 0),
  current_stock numeric(14,3) not null default 0 check (current_stock >= 0),
  minimum_stock numeric(14,3) not null default 0 check (minimum_stock >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  ingredient_id uuid not null references public.ingredients(id) on delete cascade,
  movement_type text not null check (movement_type in ('purchase','adjustment_in','waste','adjustment_out','sale')),
  quantity numeric(14,3) not null,
  unit_cost numeric(14,4) not null default 0,
  supplier text,
  note text,
  order_id uuid references public.orders(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.product_recipes (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  ingredient_id uuid not null references public.ingredients(id) on delete cascade,
  quantity numeric(14,3) not null check (quantity > 0),
  created_at timestamptz not null default now(),
  unique(product_id, ingredient_id)
);

alter table public.ingredients enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.product_recipes enable row level security;

drop policy if exists "Admins gestionan ingredientes" on public.ingredients;
create policy "Admins gestionan ingredientes" on public.ingredients
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins gestionan movimientos" on public.inventory_movements;
create policy "Admins gestionan movimientos" on public.inventory_movements
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins gestionan recetas" on public.product_recipes;
create policy "Admins gestionan recetas" on public.product_recipes
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create or replace function public.register_inventory_movement(
  ingredient_id uuid,
  movement_type text,
  quantity numeric,
  unit_cost numeric default 0,
  supplier text default null,
  note text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'No autorizado';
  end if;
  if quantity = 0 then
    raise exception 'La cantidad no puede ser cero';
  end if;
  if not exists(select 1 from public.ingredients where id=ingredient_id) then
    raise exception 'Ingrediente no encontrado';
  end if;
  if (select current_stock + quantity from public.ingredients where id=ingredient_id) < 0 then
    raise exception 'El movimiento dejaría el stock en negativo';
  end if;

  update public.ingredients
  set current_stock=current_stock+quantity,
      cost_per_unit=case when quantity>0 and unit_cost>0 then unit_cost else cost_per_unit end,
      updated_at=now()
  where id=ingredient_id;

  insert into public.inventory_movements
    (ingredient_id,movement_type,quantity,unit_cost,supplier,note,created_by)
  values
    (ingredient_id,movement_type,quantity,coalesce(unit_cost,0),supplier,note,auth.uid());
end;
$$;

grant execute on function public.register_inventory_movement(uuid,text,numeric,numeric,text,text) to authenticated;

create or replace function public.deduct_inventory_for_order_item()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recipe record;
  deduction numeric;
begin
  for recipe in
    select ingredient_id, quantity
    from public.product_recipes
    where product_id=new.product_id
  loop
    deduction := recipe.quantity * new.quantity;

    update public.ingredients
    set current_stock=greatest(0,current_stock-deduction),
        updated_at=now()
    where id=recipe.ingredient_id;

    insert into public.inventory_movements
      (ingredient_id,movement_type,quantity,unit_cost,note,order_id)
    values
      (recipe.ingredient_id,'sale',-deduction,0,'Descuento automático por venta',new.order_id);
  end loop;
  return new;
end;
$$;

drop trigger if exists trg_deduct_inventory_order_item on public.order_items;
create trigger trg_deduct_inventory_order_item
after insert on public.order_items
for each row execute function public.deduct_inventory_for_order_item();

create index if not exists idx_inventory_movements_ingredient on public.inventory_movements(ingredient_id);
create index if not exists idx_inventory_movements_created_at on public.inventory_movements(created_at desc);
create index if not exists idx_product_recipes_product on public.product_recipes(product_id);
