-- MORDISCO OS V41 · AMIGOS MORDISCO REAL
-- Ejecutar en Supabase SQL Editor.
-- Seguro para ejecutar después de 24_V40_AMIGOS_MORDISCO.sql.

create extension if not exists pgcrypto;

create table if not exists public.amigos_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 2 and 40),
  birth_date date not null,
  city text not null default 'Machala',
  looking_for text not null check (looking_for in ('amistad','citas','ambos')),
  bio text default '' check (char_length(bio)<=300),
  interests text[] not null default '{}',
  photo_url text,
  active boolean not null default true,
  verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint amigos_adult_only check (birth_date <= (current_date - interval '18 years')::date)
);
alter table public.amigos_profiles add column if not exists updated_at timestamptz not null default now();

create table if not exists public.amigos_swipes (
  id bigint generated by default as identity primary key,
  from_user uuid not null references auth.users(id) on delete cascade,
  to_user uuid not null references auth.users(id) on delete cascade,
  decision text not null check (decision in ('like','pass')),
  created_at timestamptz not null default now(),
  unique(from_user,to_user), check(from_user<>to_user)
);
create table if not exists public.amigos_blocks (
  blocker uuid not null references auth.users(id) on delete cascade,
  blocked uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(blocker,blocked), check(blocker<>blocked)
);
create table if not exists public.amigos_reports (
  id bigint generated by default as identity primary key,
  reporter uuid not null references auth.users(id) on delete cascade,
  reported uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  details text default '',
  status text not null default 'open' check(status in ('open','reviewed','closed')),
  created_at timestamptz not null default now()
);
create table if not exists public.amigos_date_proposals (
  id bigint generated by default as identity primary key,
  proposer uuid not null references auth.users(id) on delete cascade,
  invitee uuid not null references auth.users(id) on delete cascade,
  proposed_at timestamptz not null,
  message text default '' check(char_length(message)<=180),
  status text not null default 'pending' check(status in ('pending','accepted','declined','cancelled')),
  created_at timestamptz not null default now(),
  check(proposer<>invitee)
);
alter table public.amigos_date_proposals add column if not exists message text default '';

create table if not exists public.amigos_messages (
  id bigint generated by default as identity primary key,
  sender uuid not null references auth.users(id) on delete cascade,
  receiver uuid not null references auth.users(id) on delete cascade,
  body text not null check(char_length(body) between 1 and 600),
  created_at timestamptz not null default now(),
  read_at timestamptz,
  check(sender<>receiver)
);
create index if not exists amigos_messages_parties_idx on public.amigos_messages(sender,receiver,created_at);
create index if not exists amigos_swipes_match_idx on public.amigos_swipes(from_user,to_user,decision);

alter table public.amigos_profiles enable row level security;
alter table public.amigos_swipes enable row level security;
alter table public.amigos_blocks enable row level security;
alter table public.amigos_reports enable row level security;
alter table public.amigos_date_proposals enable row level security;
alter table public.amigos_messages enable row level security;

-- Políticas propias de perfiles
 drop policy if exists amigos_profile_own_select on public.amigos_profiles;
 drop policy if exists amigos_profile_own_insert on public.amigos_profiles;
 drop policy if exists amigos_profile_own_update on public.amigos_profiles;
 drop policy if exists amigos_profile_own_delete on public.amigos_profiles;
create policy amigos_profile_own_select on public.amigos_profiles for select to authenticated using (auth.uid()=user_id);
create policy amigos_profile_own_insert on public.amigos_profiles for insert to authenticated with check (auth.uid()=user_id);
create policy amigos_profile_own_update on public.amigos_profiles for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy amigos_profile_own_delete on public.amigos_profiles for delete to authenticated using (auth.uid()=user_id);

-- Swipes: cada usuario escribe los suyos y puede ver los que lo involucran.
drop policy if exists amigos_swipes_own_select on public.amigos_swipes;
drop policy if exists amigos_swipes_own_write on public.amigos_swipes;
drop policy if exists amigos_swipes_own_update on public.amigos_swipes;
create policy amigos_swipes_own_select on public.amigos_swipes for select to authenticated using (auth.uid()=from_user or auth.uid()=to_user);
create policy amigos_swipes_own_write on public.amigos_swipes for insert to authenticated with check (auth.uid()=from_user);
create policy amigos_swipes_own_update on public.amigos_swipes for update to authenticated using (auth.uid()=from_user) with check (auth.uid()=from_user);

-- Bloqueos y reportes
drop policy if exists amigos_blocks_own on public.amigos_blocks;
drop policy if exists amigos_blocks_insert on public.amigos_blocks;
drop policy if exists amigos_blocks_delete on public.amigos_blocks;
create policy amigos_blocks_own on public.amigos_blocks for select to authenticated using (auth.uid()=blocker);
create policy amigos_blocks_insert on public.amigos_blocks for insert to authenticated with check (auth.uid()=blocker);
create policy amigos_blocks_delete on public.amigos_blocks for delete to authenticated using (auth.uid()=blocker);
drop policy if exists amigos_reports_insert on public.amigos_reports;
drop policy if exists amigos_reports_own_select on public.amigos_reports;
create policy amigos_reports_insert on public.amigos_reports for insert to authenticated with check (auth.uid()=reporter);
create policy amigos_reports_own_select on public.amigos_reports for select to authenticated using (auth.uid()=reporter);

-- Helpers: existe Match mutuo.
create or replace function public.amigos_is_match(a uuid,b uuid)
returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from amigos_swipes x where x.from_user=a and x.to_user=b and x.decision='like')
    and exists(select 1 from amigos_swipes y where y.from_user=b and y.to_user=a and y.decision='like')
    and not exists(select 1 from amigos_blocks z where (z.blocker=a and z.blocked=b) or (z.blocker=b and z.blocked=a));
$$;
revoke all on function public.amigos_is_match(uuid,uuid) from public;
grant execute on function public.amigos_is_match(uuid,uuid) to authenticated;

-- Citas: únicamente entre Matches.
drop policy if exists amigos_dates_parties_select on public.amigos_date_proposals;
drop policy if exists amigos_dates_proposer_insert on public.amigos_date_proposals;
drop policy if exists amigos_dates_parties_update on public.amigos_date_proposals;
create policy amigos_dates_parties_select on public.amigos_date_proposals for select to authenticated using (auth.uid()=proposer or auth.uid()=invitee);
create policy amigos_dates_proposer_insert on public.amigos_date_proposals for insert to authenticated with check (auth.uid()=proposer and public.amigos_is_match(proposer,invitee));
create policy amigos_dates_parties_update on public.amigos_date_proposals for update to authenticated using (auth.uid()=proposer or auth.uid()=invitee) with check (auth.uid()=proposer or auth.uid()=invitee);

-- Mensajes únicamente entre Matches.
drop policy if exists amigos_messages_parties_select on public.amigos_messages;
drop policy if exists amigos_messages_match_insert on public.amigos_messages;
drop policy if exists amigos_messages_receiver_update on public.amigos_messages;
create policy amigos_messages_parties_select on public.amigos_messages for select to authenticated using ((auth.uid()=sender or auth.uid()=receiver) and public.amigos_is_match(sender,receiver));
create policy amigos_messages_match_insert on public.amigos_messages for insert to authenticated with check (auth.uid()=sender and public.amigos_is_match(sender,receiver));
create policy amigos_messages_receiver_update on public.amigos_messages for update to authenticated using (auth.uid()=receiver) with check (auth.uid()=receiver);

-- Directorio seguro: no expone correo, teléfono, fecha de nacimiento exacta ni user metadata.
create or replace function public.amigos_get_discovery(p_limit integer default 60)
returns table(user_id uuid,display_name text,age integer,city text,looking_for text,bio text,interests text[],photo_url text,verified boolean)
language sql stable security definer set search_path=public as $$
 select p.user_id,p.display_name,
        extract(year from age(current_date,p.birth_date))::integer as age,
        p.city,p.looking_for,p.bio,p.interests,p.photo_url,p.verified
 from amigos_profiles p
 where auth.uid() is not null
   and p.active=true and p.user_id<>auth.uid()
   and not exists(select 1 from amigos_blocks b where (b.blocker=auth.uid() and b.blocked=p.user_id) or (b.blocker=p.user_id and b.blocked=auth.uid()))
   and not exists(select 1 from amigos_swipes s where s.from_user=auth.uid() and s.to_user=p.user_id)
 order by p.created_at desc
 limit greatest(1,least(coalesce(p_limit,60),100));
$$;
revoke all on function public.amigos_get_discovery(integer) from public;
grant execute on function public.amigos_get_discovery(integer) to authenticated;

create or replace function public.amigos_get_matches()
returns table(user_id uuid,display_name text,age integer,city text,looking_for text,bio text,interests text[],photo_url text,verified boolean,matched_at timestamptz)
language sql stable security definer set search_path=public as $$
 select p.user_id,p.display_name,
        extract(year from age(current_date,p.birth_date))::integer as age,
        p.city,p.looking_for,p.bio,p.interests,p.photo_url,p.verified,
        greatest(a.created_at,b.created_at) as matched_at
 from amigos_swipes a
 join amigos_swipes b on b.from_user=a.to_user and b.to_user=a.from_user and b.decision='like'
 join amigos_profiles p on p.user_id=a.to_user and p.active=true
 where a.from_user=auth.uid() and a.decision='like'
   and not exists(select 1 from amigos_blocks bl where (bl.blocker=auth.uid() and bl.blocked=p.user_id) or (bl.blocker=p.user_id and bl.blocked=auth.uid()))
 order by greatest(a.created_at,b.created_at) desc;
$$;
revoke all on function public.amigos_get_matches() from public;
grant execute on function public.amigos_get_matches() to authenticated;

create or replace function public.amigos_get_messages(p_other_user uuid,p_limit integer default 120)
returns table(id bigint,sender uuid,receiver uuid,body text,created_at timestamptz,read_at timestamptz)
language plpgsql security definer set search_path=public as $$
begin
 if auth.uid() is null or not public.amigos_is_match(auth.uid(),p_other_user) then raise exception 'No existe un Match activo'; end if;
 return query select m.id,m.sender,m.receiver,m.body,m.created_at,m.read_at from amigos_messages m
 where (m.sender=auth.uid() and m.receiver=p_other_user) or (m.sender=p_other_user and m.receiver=auth.uid())
 order by m.created_at asc limit greatest(1,least(coalesce(p_limit,120),300));
end $$;
revoke all on function public.amigos_get_messages(uuid,integer) from public;
grant execute on function public.amigos_get_messages(uuid,integer) to authenticated;

-- Actualización automática de updated_at.
create or replace function public.amigos_touch_profile() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
drop trigger if exists amigos_profiles_touch on public.amigos_profiles;
create trigger amigos_profiles_touch before update on public.amigos_profiles for each row execute function public.amigos_touch_profile();

-- Fotos públicas de perfil. Cada usuario solo escribe dentro de su carpeta /<uid>/.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('amigos-profile-photos','amigos-profile-photos',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=true,file_size_limit=5242880,allowed_mime_types=array['image/jpeg','image/png','image/webp'];

drop policy if exists amigos_photo_insert on storage.objects;
drop policy if exists amigos_photo_update on storage.objects;
drop policy if exists amigos_photo_delete on storage.objects;
create policy amigos_photo_insert on storage.objects for insert to authenticated with check (bucket_id='amigos-profile-photos' and (storage.foldername(name))[1]=auth.uid()::text);
create policy amigos_photo_update on storage.objects for update to authenticated using (bucket_id='amigos-profile-photos' and (storage.foldername(name))[1]=auth.uid()::text) with check (bucket_id='amigos-profile-photos' and (storage.foldername(name))[1]=auth.uid()::text);
create policy amigos_photo_delete on storage.objects for delete to authenticated using (bucket_id='amigos-profile-photos' and (storage.foldername(name))[1]=auth.uid()::text);

-- Realtime para chat (si ya existe en la publicación, ignorar el duplicate_object).
do $$ begin
  alter publication supabase_realtime add table public.amigos_messages;
exception when duplicate_object then null; end $$;

-- Permisos básicos.
grant select,insert,update,delete on public.amigos_profiles to authenticated;
grant select,insert,update on public.amigos_swipes to authenticated;
grant select,insert,delete on public.amigos_blocks to authenticated;
grant select,insert on public.amigos_reports to authenticated;
grant select,insert,update on public.amigos_date_proposals to authenticated;
grant select,insert,update on public.amigos_messages to authenticated;
